
FROM openjdk:17
COPY target/BeingAbroad-0.0.1-SNAPSHOT.jar BeingAbroad-0.0.1-SNAPSHOT.jar
COPY src/main/resources/application.properties /app/config/application.properties
CMD java -jar BeingAbroad-0.0.1-SNAPSHOT.jar